apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-nginx-replicaset
spec:
  replicas: 4  # Vous pouvez ajuster le nombre de réplicas en fonction de vos besoins
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: registry.cluster.wik.cloud/public/echo
        ports:
        - containerPort: 80
